# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 100
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /redisinsight
    schedule:
      interval: weekly
  - package-ecosystem: npm
    open-pull-requests-limit: 100
    directory: /redisinsight/api
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /redisinsight/ui/src/packages/redisearch
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /redisinsight/ui/src/packages/clients-list-example
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /redisinsight/ui/src/packages/redis-app-plugin-api
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /tests/e2e
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
